name: Run pytest

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dune-daq/nightly-release-alma9:development_v5
    steps:
      - name: Set up dev nightly
        run: |
          mkdir nightly
          cd nightly
          source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
          setup_dbt latest_v5
          dbt-create -n last-fddaq
          cd NFD_DEV*
          source env.sh
          dbt-build
          dbt-workarea-env
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          git clone https://github.com/DUNE-DAQ/druncschema.git -b ${{ github.ref_name }} ||  git clone https://github.com/DUNE-DAQ/druncschema.git
          git clone https://github.com/DUNE-DAQ/drunc.git -b ${{ github.ref_name }}
          cd druncschema
          pip install .
          cd -
          cd drunc
          pip install .
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
