name: Run pytest

on:
  push:

jobs:
  install_and_test:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/dune-daq/nightly-release-alma9:development_v5

    steps:
      - name: Set up dev nightly
        run: |
          mkdir nightly
          cd nightly
          source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
          setup_dbt latest_v5
          dbt-create -n last_fddaq
          cd NFD_DEV*
          source env.sh
          dbt-build
          dbt-workarea-env

      - name: Install druncschema and drunc
        run: |
          cd nightly/NFD_DEV* || true
          source env.sh
          python -m pip install --upgrade pip
          git clone https://github.com/DUNE-DAQ/druncschema.git -b ${{ github.ref_name }} ||  git clone https://github.com/DUNE-DAQ/druncschema.git
          git clone https://github.com/DUNE-DAQ/drunc.git -b ${{ github.ref_name }}
          cd druncschema
          pip install .
          cd -
          cd drunc
          pip install .

      - name: Test with pytest/pytest-cov
        run: |
          cd nightly/NFD_DEV* || true
          source env.sh
          cd drunc || true
          pip install pytest pytest-cov
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=drunc --cov-report=xml --cov-report=html

      - name: Upload JUnit test report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: nightly/NFD_DEV*/junit/test-results.xml

      - name: Upload coverage report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: nightly/NFD_DEV*/htmlcov/

      - name: Upload coverage report (XML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: nightly/NFD_DEV*/coverage.xml